name: Java CI/CD - Pet Rock Caretaker Simulator

on:
  push:
    branches:
      - main
      - lucas
      - Abe
  pull_request:
    branches:
      - main
      - lucas
      - Abe

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Install Dependencies
      run: mvn clean install -DskipTests

    - name: Run Unit Tests
      run: mvn test

    - name: Checkstyle Validation
      run: mvn checkstyle:check

    - name: Build Project
      run: mvn package

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PetRockSimulator
        path: target/*.jar
