name: Java Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Compile Maven project
        run: mvn compile
      
      - name: Package (Build) Project
        run: mvn package
      
      - name: Run Program
        run: java -jar target/petrock_project-1.0-SNAPSHOT.jar
      
      - name: Rebuild if any issues
        run: mvn clean package
