name: Java Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Change to project directory
        run: cd ${{ github.workspace }}/petrock_project
      
      - name: Compile Maven project
        run: mvn compile
        working-directory: ${{ github.workspace }}/petrock_project
      
      - name: Package (Build) Project
        run: mvn package
        working-directory: ${{ github.workspace }}/petrock_project
      
      - name: Rebuild if any issues
        run: mvn clean package
        working-directory: ${{ github.workspace }}/petrock_project
